version: "3.9"

services:
  node:
    command: ["sh", "-c", "npm install && npm run dev"]
    image: node:lts-alpine
    ports:
      - "4321:4321"
    volumes:
      - .:/repo
    working_dir: /repo
